POST http://localhost:8080/entries
Content-Type: application/json

{
  "courseName": "Test",
  "management": "Test",
  "place": "Test",
  "weekDay": "Test",
  "courseTime": "19:30:00",
  "startDate": "2024-03-01",
  "endDate": "2024-07-30"
}

