POST http://localhost:8080/entries
Content-Type: application/json

{
  "courseName": "Test",
  "management": "Test",
  "place": "Test",
  "weekDay": "Test",
  "courseTime": "10:30:00",
  "startDate": "2024-06-01",
  "endDate": "2024-06-30"
}