POST http://localhost:8080/entries
Content-Type: application/json

{
  "courseName": "Aerobics",
  "management": "Angelo Merte",
  "place": "HTW Wilhelminenhof",
  "weekDay": "Donnerstag",
  "courseTime": "19:30:00",
  "startDate": "2024-03-01",
  "endDate": "2024-07-30"
}

