name: Deploy to Render

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Distribution of JDK (AdoptOpenJDK is now Eclipse Temurin)
          java-version: '20'       # Change to the required Java version

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests with Gradle
        run: ./gradlew test

      - name: Deploy to Render
        if: success()
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
            -H 'Authorization: Bearer $RENDER_API_KEY' \
            -H 'Content-Type: application/json' \
            -d '{"serviceId": "YOUR_SERVICE_ID", "clearCache": false}' \
            https://api.render.com/v1/services/YOUR_SERVICE_ID/deploys
